export const NavCategories = [
  {
    name: "Women",
    slug: "women",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          "Tops",
          "Bottoms",
          "Dresses",
          "Jackets | Coats | Hoodies",
          "Activewear",
          "Lingerie & Pyjamas",
          // "Shoes",
          // "Accessories",
        ],
      },
      {
        name: "Shoes",
        subcategories: ["Heels", "Flats", "Sandals", "Boots", "Sneakers"],
      },
      {
        name: "Bags",
        subcategories: [
          "Backpacks",
          "Totes & Shoulder Bags",
          "Handbags",
          "Luggage & Travel",
          "Clutches & Evening Bags",
        ],
      },
      {
        name: "Accessories",
        subcategories: [
          "Hair accessories",
          "Scarves & shawls",
          "Hats & caps",
          "Sunglasses",
          "Watches",
          "Jewelry",
          "Other accessories",
        ],
      },
      {
        name: "Beauty",
        subcategories: [
          "Perfume",
          "Beauty tools",
          "Nail care",
          "Hair care",
          "Makeup",
          "Facial care",
          "Hand care",
          "Body care",
          "Other beauty items",
        ],
      },
    ],
  },
  {
    name: "Men",
    slug: "men",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          "Tops",
          "Bottoms",
          "Jackets | Coats | Hoodies",
          "Activewear",
          "Underwear",

          "Suits",
        ],
      },
      {
        name: "Shoes",
        subcategories: [
          "Dress Shoes",
          "Casual Shoes",
          "Sandals",
          "Boots",
          "Sneakers",
        ],
      },
      {
        name: "Accessories",
        subcategories: [
          "Hats & caps",
          "Sunglasses",
          "Watches",
          "Jewelry",
          "Bags & backpacks",
          "Other accessories",
        ],
      },
      {
        name: "Grooming",
        subcategories: [
          "Tools & accessories",
          "Aftershave & cologne",
          "Facial care",
          "Hair care",
          "Other grooming items",
        ],
      },
    ],
  },
  {
    name: "Kids",
    slug: "kids",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          "Tops",
          "Bottoms",
          "Dresses",
          "Jackets | Coats | Hoodies",
          "Activewear",
          "Sleepwear",
          "Accessories",
        ],
      },
      {
        name: "Shoes",
        subcategories: ["Casual Shoes", "Sandals", "Boots", "Sneakers"],
      },
    ],
  },
  {
    name: "Traditional Wear",
    slug: "traditional-wear",
    subcategories: [
      { name: "Men", subcategories: [] },
      { name: "Women", subcategories: [] },
    ],
  },
];

export const NavCategoriesWithSizes = [
  {
    name: "Women",
    slug: "women",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          { name: "Tops", sizes: ["S", "M", "L", "XL"] },
          {
            name: "Bottoms",
            sizes: [
              "24",
              "25",
              "26",
              "27",
              "28",
              "29",
              "30",
              "31",
              "32",
              "33",
              "34",
              "36",
              "38",
              "40",
              "42",
              "44",
              "46",
              "48",
              "50",
              "52",
              "54",
              "56",
            ],
          },
          {
            name: "Dresses",
            sizes: [
              "32",
              "34",
              "36",
              "38",
              "40",
              "42",
              "44",
              "46",
              "48",
              "50",
              "52",
              "54",
            ],
          },
          { name: "Jackets | Coats | Hoodies", sizes: [] },
          { name: "Activewear", sizes: ["S", "M", "L", "XL"] },
          {
            name: "Lingerie & Pyjamas",
            sizes: [
              "65A",
              "65B",
              "65C",
              "65D",
              "65E",
              "65F",
              "65G",
              "65H",
              "65I",
              "65J",
              "65K",
              "70A",
              "70B",
              "70C",
              "70D",
              "70E",
              "70F",
              "70G",
              "70H",
              "70I",
              "70J",
              "70K",
              "75A",
              "75B",
              "75C",
              "75D",
              "75E",
              "75F",
              "75G",
              "75H",
              "75I",
              "75J",
              "75K",
              "80A",
              "80B",
              "80C",
              "80D",
              "80E",
              "80F",
              "80G",
              "80H",
              "80I",
              "80J",
              "80K",
              "85A",
              "85B",
              "85C",
              "85D",
              "85E",
              "85F",
              "85G",
              "85H",
              "85I",
              "85J",
              "85K",
              "90A",
              "90B",
              "90C",
              "90D",
              "90E",
              "90F",
              "90G",
              "90H",
              "90I",
              "90J",
              "90K",
              "95A",
              "95B",
              "95C",
              "95D",
              "95E",
              "95F",
              "95G",
              "95H",
              "95I",
              "95J",
              "95K",
              "100A",
              "100B",
              "100C",
              "100D",
              "100E",
              "100F",
              "100G",
              "100H",
              "100I",
              "100J",
              "100K",
            ],
          },
          // {
          //   name: "Shoes",
          //   sizes: [
          //     "2.5",
          //     "3",
          //     "3.5",
          //     "4",
          //     "4.5",
          //     "5",
          //     "5.5",
          //     "6",
          //     "6.5",
          //     "7",
          //     "7.5",
          //     "8",
          //     "8.5",
          //     "9",
          //     "9.5",
          //   ],
          // },
          // { name: "Accessories", sizes: [] },
        ],
      },
      {
        name: "Shoes",
        subcategories: [
          { name: "Heels", sizes: ["5", "6", "7", "8", "9", "10"] },
          { name: "Flats", sizes: ["5", "6", "7", "8", "9", "10"] },
          { name: "Sandals", sizes: ["5", "6", "7", "8", "9", "10"] },
          { name: "Boots", sizes: ["5", "6", "7", "8", "9", "10"] },
          { name: "Sneakers", sizes: ["5", "6", "7", "8", "9", "10"] },
        ],
      },
      {
        name: "Bags",
        subcategories: [
          { name: "Backpacks", sizes: [] },
          { name: "Totes & Shoulder Bags", sizes: [] },
          { name: "Handbags", sizes: [] },
          { name: "Luggage & Travel", sizes: [] },
          { name: "Clutches & Evening Bags", sizes: [] },
        ],
      },
      {
        name: "Accessories",
        subcategories: [
          { name: "Hair accessories", sizes: [] },
          { name: "Hats & caps", sizes: [] },
          { name: "Scarves & shawls", sizes: [] },
          { name: "Sunglasses", sizes: [] },
          { name: "Other accessories", sizes: [] },
          { name: "Jewelry", sizes: [] },
          { name: "Watches", sizes: [] },
        ],
      },
      {
        name: "Beauty",
        subcategories: [
          { name: "Perfume", sizes: [] },
          { name: "Beauty tools", sizes: [] },
          { name: "Nail care", sizes: [] },
          { name: "Hair care", sizes: [] },
          { name: "Makeup", sizes: [] },
          { name: "Facial care", sizes: [] },
          { name: "Hand care", sizes: [] },
          { name: "Body care", sizes: [] },
          { name: "Other beauty items", sizes: [] },
        ],
      },
    ],
  },
  {
    name: "Men",
    slug: "men",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          { name: "Tops", sizes: ["S", "M", "L", "XL", "XXL"] },
          {
            name: "Bottoms",
            sizes: [
              "28",
              "30",
              "32",
              "34",
              "36",
              "38",
              "40",
              "42",
              "44",
              "46",
              "48",
              "50",
              "52",
              "54",
              "56",
            ],
          },

          { name: "Jackets | Coats | Hoodies", sizes: [] },
          { name: "Activewear", sizes: ["S", "M", "L", "XL"] },
          { name: "Underwear", sizes: ["S", "M", "L", "XL"] },
          // {
          //   name: "Shoes",
          //   sizes: [
          //     "6",
          //     "6.5",
          //     "7",
          //     "7.5",
          //     "8",
          //     "8.5",
          //     "9",
          //     "9.5",
          //     "10",
          //     "10.5",
          //     "11",
          //     "11.5",
          //     "12",
          //   ],
          // },
          // { name: "Accessories", sizes: [] },
          {
            name: "Suits",
            sizes: [
              "34",
              "36",
              "38",
              "40",
              "42",
              "44",
              "46",
              "48",
              "50",
              "52",
              "54",
            ],
          },
        ],
      },
      {
        name: "Shoes",
        subcategories: [
          {
            name: "Dress Shoes",
            sizes: [
              "6",
              "6.5",
              "7",
              "7.5",
              "8",
              "8.5",
              "9",
              "9.5",
              "10",
              "10.5",
              "11",
              "12",
              "13",
              "14",
            ],
          },
          {
            name: "Casual Shoes",
            sizes: [
              "6",
              "6.5",
              "7",
              "7.5",
              "8",
              "8.5",
              "9",
              "9.5",
              "10",
              "10.5",
              "11",
              "12",
              "13",
              "14",
            ],
          },
          {
            name: "Sandals",
            sizes: [
              "6",
              "6.5",
              "7",
              "7.5",
              "8",
              "8.5",
              "9",
              "9.5",
              "10",
              "10.5",
              "11",
              "12",
              "13",
              "14",
            ],
          },
          {
            name: "Boots",
            sizes: [
              "6",
              "6.5",
              "7",
              "7.5",
              "8",
              "8.5",
              "9",
              "9.5",
              "10",
              "10.5",
              "11",
              "12",
              "13",
              "14",
            ],
          },
          {
            name: "Sneakers",
            sizes: [
              "6",
              "6.5",
              "7",
              "7.5",
              "8",
              "8.5",
              "9",
              "9.5",
              "10",
              "10.5",
              "11",
              "12",
              "13",
              "14",
            ],
          },
        ],
      },
      {
        name: "Accessories",
        subcategories: [
          { name: "Jewelry", sizes: [] },
          { name: "Other accessories", sizes: [] },
          { name: "Bags & backpacks", sizes: [] },
          { name: "Hats & caps", sizes: [] },
          { name: "Sunglasses", sizes: [] },
          { name: "Watches", sizes: [] },
        ],
      },
      {
        name: "Grooming",
        subcategories: [
          { name: "Tools & accessories", sizes: [] },
          { name: "Aftershave & cologne", sizes: [] },
          { name: "Facial care", sizes: [] },
          { name: "Hair care", sizes: [] },
          { name: "Other grooming items", sizes: [] },
        ],
      },
    ],
  },
  {
    name: "Kids",
    slug: "kids",
    subcategories: [
      {
        name: "Clothing",
        subcategories: [
          { name: "Tops", sizes: [] },
          { name: "Bottoms", sizes: [] },
          {
            name: "Dresses",
            sizes: [
              "3-6 months",
              "6-9 months",
              "9-12 months",
              "12-18 months",
              "18-24 months",
              "2-3 years",
              "3-4 years",
              "4-5 years",
              "5-6 years",
              "6-7 years",
              "7-8 years",
              "8-9 years",
              "9-10 years",
              "10-11 years",
              "11-12 years",
              "12-13 years",
              "13-14 years",
            ],
          },
          { name: "Jackets | Coats | Hoodies", sizes: [] },
          { name: "Activewear", sizes: [] },
          { name: "Sleepwear", sizes: [] },
          { name: "Accessories", sizes: [] },
        ],
      },

      {
        name: "Shoes",
        subcategories: [
          {
            name: "Casual Shoes",
            sizes: ["10", "11", "12", "13", "1", "2", "3", "4", "5"],
          },
          {
            name: "Sandals",
            sizes: ["10", "11", "12", "13", "1", "2", "3", "4", "5"],
          },
          {
            name: "Boots",
            sizes: ["10", "11", "12", "13", "1", "2", "3", "4", "5"],
          },
          {
            name: "Sneakers",
            sizes: ["10", "11", "12", "13", "1", "2", "3", "4", "5"],
          },
        ],
      },
    ],
  },
  {
    name: "Traditional Wear",
    slug: "traditional-wear",
    subcategories: [
      { name: "Men", subcategories: [] },
      { name: "Women", subcategories: [] },
    ],
  },
];
